--vim.filetype.add({
--	pattern = {
--		[".*"] = {
--			priority = math.huge,
--			function(_, bufnr)
--				local line1 = vim.api.nvim_buf_get_lines(bufnr, 1, 1, false)[1] or ''
--				local line2 = vim.api.nvim_buf_get_lines(bufnr, 2, 1, false)[2] or ''
--				if
--					vim.regex(line1, [[^AWSTemplateFormatVersion]])
--					or vim.regex(line2, [[AWS::Serverless-2016-10-31]])
--				then
--					return "yaml.cloudformation"
--				end
--			end,
--		},
--	},
--})
